POST https://if.caiyunai.com/v2/novel/6198dd040e13ac54b7ba8cfc/novel_ai
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Host: if.caiyunai.com
Origin: https://if.caiyunai.com
Referer: https://if.caiyunai.com/dream/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34

{
  "nid": "",
  "content": "续写\n我们这个时代的人类还没有意识到自己所拥有的资源和实力会给自己带来多大的危险性。所谓人心易变。在这样一种情况下，很容易会产生变化。\n而且这些人类也是非常容易就被诱惑和利用的存在，比如现在",
  "uid": "",
  "mid": "",
  "title": "",
  "status": "http",
  "storyline": false,
  "lastnode": "",
  "ostype": "",
  "lang": "zh"
}

###